### ISSUE TITLE
Getting started with design

### ISSUE THREAD

**Issue by MiquelToni** [ramikate/ratesOFmine#7]
Before jumping right into code we must plan a bit what we want. How do we want the buttons to look like, the primary, secondary and accent colors, and stuff...
This is not development but designers task. Being full-stack, means that sometimes, we will need to jump into it too. So, we better get used to what are the best practices for UI design and tooling.

Note that there are a lot of libraries and guidelines like [Material Design](https://m3.material.io/) that can easy a lot development and design at a cost of a "not so custom" look.
There are many Apple, Microsoft and any big corp have their own... It's just a matter to decide pick a guideline or go full custom.
*most of the packages have customization options. Not so flexy, but a lot of stuff it's already implemented.

On the tooling side one of the most recognized is [Figma](https://www.figma.com). For the designers is the platform to build their creations and share them with the developers. For the developers, we can check what the designer built and the CSS parameters.
Make sure your designs are easy to implement!! Avoid using absolute positioning, instead use padding, margin and gap to set the layout. Also avoid setting sizes in pixels, use [`rem`](https://www.w3schools.com/cssref/css_units.php) instead.

## Tasks:

[ ] - Look into Material Design. (Maybe there are some js packages or pre-build components outhere :)
[ ] - Check what is Tailwind. Amazing library for building your own styles! To make the design developer friendly try to use as may tailwind classes as posible
[ ] - Join Figma and Miquel Toni's team https://www.figma.com/team_invite/redeem/1iLqLfszdh9cJRnuWZtACc
[ ] - Build a page in Figma with the main color palette. Take inspiration from the image.
[ ] - Design the home page for a screen of 1920x1080 (standard desktop)

![Image](https://github.com/ramikate/ratesOFmine/assets/13115879/ddfbd67d-1381-438c-bc53-4b8b32824747)

**Comment by MiquelToni** [comment]
Some tasks are too big to do in one sit? - Try splitting them into smaller ones :)

**Comment by ramikate** [comment]
![image](https://github.com/ramikate/ratesOFmine/assets/149439635/c8c218c3-3c9d-4114-99e5-a0128bdfced1)

This is not free to use :(
